### ISSUE TITLE
Automate versioning and releases

### ISSUE THREAD

**Issue by Glusk** [Glusk/sprouts#161]
Resources:
  - [rultor](https://doc.rultor.com/)
  - https://github.com/researchgate/gradle-release
  - <del>https://stackoverflow.com/questions/21405457</del> (We don't want to increment `versionCode` on every build)

**Comment by Glusk2** [comment]
@rultor hello

**Comment by Glusk2** [comment]
`.rultor.yml` draft:

``` yml
architect:
  - Glusk2
release:
  script: "" #todo
```

**Comment by Glusk2** [comment]
bash script to increment `versionCode` (adopted from https://stackoverflow.com/questions/38366410):
``` bash
perl -i.orig -pe '/versionCode/ && s/(\d+)/$1+1 . $2/e' android/build.gradle
```

**Comment by Glusk2** [comment]
Badge:
[![DevOps By Rultor.com](http://www.rultor.com/b/yegor256/rultor)](http://www.rultor.com/p/Glusk2/sprouts)

**Comment by Glusk2** [comment]
Gradle release plugin requires to have the version stored in `gradle.properties`

**Comment by Glusk2** [comment]
Keeps failing with:

```
Execution failed for task ':sprouts:checkCommitNeeded'.
> You have uncommitted files:
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   M build.gradle
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Glusk2** [comment]
It doesn't work! Still reports uncommited when trying to run the `release` plugin.

**Comment by Glusk2** [comment]
I'm giving up `gradle-release` plugin!

**Comment by Glusk2** [comment]
Manually pick out `gradle-release` steps

1.  ``` bash
    echo "$tag" | ./gradlew updateVersion
    ```
2.  ``` bash
    git commit -am "$tag"
    ```
3.  ``` bash
    # create a new tag for the latest commit
    ```
4.  ``` bash
    echo "$tag-SNAPSHOT" | ./gradlew updateVersion
    ```
5.  ``` bash
    git commit -am "$tag-SNAPSHOT"

**Comment by Glusk2** [comment]
Rultor only pushes the release tag. Because it doesn't push to `master`, the version doesn't get updated.

**Comment by Glusk2** [comment]
How about this:
https://help.github.com/en/github/automating-your-workflow-with-github-actions/creating-a-docker-container-action
?

**Comment by Glusk2** [comment]
Sample action yml:

``` yml
on:
  issue_comment:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@master
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8 
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.0.2
        run: ./$ANDROID_HOME/tools/bin/sdkmanager "platforms;android-28" "platform-tools" "build-tools;28.0.3"
      - name: Bump versions to a new tag
        run: |
          perl -i.orig -pe '/versionCode/ && s/([0-9]+)/$1+1 . $2/e' android/build.gradle
          # Get the tag from ${{ github.event.comment.body }}
          version=${tag#"v"}
          chmod +x gradlew
          ./gradlew updateVersion -Prelease.useAutomaticVersion=true -Prelease.newVersion=$version
      - name: Run a test build
        run: ./gradlew build connectedCheck
      - name: Tag the new version
        run: |
          git commit -am "Bumped project version to $tag"
          git tag -a v1.4 -m "Release $tag"
          ./gradlew updateVersion -Prelease.useAutomaticVersion=true -Prelease.newVersion=$version-SNAPSHOT
          git commit -am "Bumped project version to $tag-SNAPSHOT"
      - name: Create local changes
        run: |
          ...
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
```
